name: bookshop-connector
version: 0.1.0
id: 743f7a4e-7ce7-4ebc-b667-2346bbde85bf
description: "Bookshop Connector to demonstrate the installation and consumption of kyma addons"
bindable: true
displayName: "Bookshop Connector"
providerDisplayName: "SAP"
imageURL: https://previews.123rf.com/images/vtmila/vtmila1707/vtmila170700060/82498902-open-book-hardback-books-on-bright-colorful-background-.jpg